
NIFTY_50_SYMBOLS = [
    "RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS",
    "ICICIBANK.NS", "LT.NS", "SBIN.NS", "BHARTIARTL.NS",
    "ITC.NS", "HINDUNILVR.NS", "AXISBANK.NS", "KOTAKBANK.NS",
    "ASIANPAINT.NS", "BAJFINANCE.NS", "MARUTI.NS",
    "SUNPHARMA.NS", "TITAN.NS", "ULTRACEMCO.NS",
    "WIPRO.NS", "ONGC.NS"
]
